name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: Tech support does not belong here. You should only file an issue here if you think you have experienced an actual bug with Borked3DS.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: input
    attributes:
      label: Affected Build(s)
      description: List the affected build(s) that this issue applies to.
      placeholder: ex. v2024.09.16a
    validations:
      required: true
  - type: input
    attributes:
      label: Sanity Check (Borked3DS)
      description: Does the issue also occur on the last official Borked3DS release (https://github.com/Borked3DS/Borked3DS/releases)?
      placeholder: Yes or No; explain.
    validations:
      required: true
  - type: input
    attributes:
      label: Sanity Check (PabloMK7)
      description: Does the issue also occur upstream on the lastest PabloMK7 release (http://github.com/PabloMK7/borked3ds/releases)?
      placeholder: Yes or No; explain.
    validations:
      required: true
  - type: input
    attributes:
      label: Sanity Check (Lime3DS)
      description: Does the issue also occur on the latest Lime3DS release (http://github.com/Lime3DS/Lime3DS-archive/releases)?
      placeholder: Yes or No; explain.
    validations:
      required: true
  - type: input
    attributes:
      label: Validation Check
      description: Is there a build where the issue does NOT occur? If so, specify which fork (ex. Borked3DS, Lime3DS, etc.) and which version things were still working properly.
      placeholder: Yes or No; explain.
    validations:
      required: true
  - type: textarea
    id: issue-desc
    attributes:
      label: Description of Issue
      description: A brief description of the issue encountered along with any images and/or videos.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A brief description of how it is expected to work along with any images and/or videos.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: A brief explanation of how to reproduce this issue. If possible, provide a save file to aid in reproducing the issue.
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log File
      description: A log file will help our developers to better diagnose and fix the issue. On Desktop, navigate to Help->Open Log Folder. On Android, go to "Share Log" in the menu or the 'log' folder in the Borked3DS User Folder.
    validations:
      required: true
  - type: textarea
    id: system-config
    attributes:
      label: System Configuration
      placeholder: |
        CPU: Intel i5-10400 / AMD Ryzen 5 3600
        GPU/Driver: NVIDIA GeForce GTX 1060 (Driver 512.95)
        RAM: 16GB DDR4-3200
        OS: Windows 11 22H2 (Build 22621.819)
        Graphics API: Vulkan, OpenGL, Both
      value: |
        CPU:
        GPU/Driver:
        RAM:
        OS:
        Graphics API:
    validations:
      required: true
