blank_issues_enabled: false
contact_links:
  - name: Borked3DS GitHub Discussions Forum
    url: https://github.com/Borked3DS/Borked3DS/discussions
    about: If you are experiencing an issue with Borked3DS, and you need tech support, or if you have a general question, try asking in the official Borked3DS GitHub Discussions forum linked here. Piracy is not allowed.
